module.exports.GENERAL = 'GENERAL'
module.exports.MODERATOR = 'MODERATOR'
module.exports.DELETE_MESSAGES = 'DELETE_MESSAGES'
module.exports.MANAGE_MESSAGES = 'MANAGE_MESSAGES'
module.exports.GUILD_OWNER = 'GUILD_OWNER'
