module.exports.BAN = 'BAN'
module.exports.KICK = 'KICK'
module.exports.PURGE = 'PURGE'
module.exports.SETTINGS = 'SETTINGS'
module.exports.COUNTING = 'COUNTING'
module.exports.AUTOROLES = 'AUTOROLES'
module.exports.OWNER_COMMANDS = 'OWNER_COMMANDS'
