module.exports.GENERAL = 'general'
module.exports.MOD_COMMAND = 'modCommand'
module.exports.GUILD_OWNER = 'guildOwner'
module.exports.BOT_OWNER = 'botOwner'
module.exports.UTILITY = 'utility'
module.exports.SOCIAL = 'social'
module.exports.GAMES = 'games'
module.exports.MUSIC = 'music'
